Base commit
Mobsman/java-filmorate pull request #18
Opened 2022-05-19 19:08 UTC by Mobsman

Base commit

2022-05-19 19:40 UTC, eugene-lenkevich requested changes
Привет,

1. таблички лучше назвать в единственном числе
2. сначала стоит нарисовать схему, в рамках этого задания не обязательно менять код, достаточно только схему :)

2022-05-19 19:40 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Genre genre;
Жанров может быть несколько, плюс наверно не стоит прибивать гвоздями набор жанров в коде, их очень много, пусть будет отдельная табличка :)

2022-05-19 20:15 UTC, Mobsman commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Genre genre;
Добрый вечер. Исправил схему базы. Но не понял почему нельзя в классе фильм использовать поле с enum жанром и рейтингом. Или делать ее просто стринг полем

2022-05-20 04:48 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Genre genre;
Рейтинг то как раз можно прибить гвоздями как enum, их ограниченное количество
А жанров полно, причем новые могут появляться https://ru.wikipedia.org/wiki/Категория:Жанры_кино

2022-05-20 04:50 UTC, eugene-lenkevich requested changes
Рейтинг можно было оставить в виде enum
А вот жанры у тебя привязаны как один-ко-многим, ноу фильма же несколько жанров может быть, это вообще вещь такая, творческая=)
Тебе нужно с жанрами связываться через многие-ко-многим, то есть через доп табличку с полями жанр_ид и фильм_ид

2022-05-20 10:19 UTC, Mobsman commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Genre genre;
Исправил

2022-05-20 10:53 UTC, eugene-lenkevich approved these changes
А рейтинг табличкой оставил, не енамом? Но в принципе можно и так, в целом все супер, спасибо

2022-06-10 14:10 UTC, merged